object CountryUtils {
    /**
     * Get emoji flag for country code
     * @param countryCode ISO 3166-1 alpha-2 country code
     * @return emoji flag for the country
     */
    private fun getFlagEmoji(countryCode: String): String {
        val firstLetter = Character.codePointAt(countryCode, 0) - 0x41 + 0x1F1E6
        val secondLetter = Character.codePointAt(countryCode, 1) - 0x41 + 0x1F1E6
        return String(Character.toChars(firstLetter)) + String(Character.toChars(secondLetter))
    }

    /**
     * Get list of all available countries
     * @return List of Country objects containing name, code and flag
     */
    fun getAllCountries(): List<Country> = listOf(
        Country("Afghanistan", "AF", getFlagEmoji("AF")),
        Country("Albania", "AL", getFlagEmoji("AL")),
        Country("Algeria", "DZ", getFlagEmoji("DZ")),
        Country("American Samoa", "AS", getFlagEmoji("AS")),
        Country("Andorra", "AD", getFlagEmoji("AD")),
        Country("Angola", "AO", getFlagEmoji("AO")),
        Country("Anguilla", "AI", getFlagEmoji("AI")),
        Country("Antarctica", "AQ", getFlagEmoji("AQ")),
        Country("Antigua and Barbuda", "AG", getFlagEmoji("AG")),
        Country("Argentina", "AR", getFlagEmoji("AR")),
        Country("Armenia", "AM", getFlagEmoji("AM")),
        Country("Aruba", "AW", getFlagEmoji("AW")),
        Country("Australia", "AU", getFlagEmoji("AU")),
        Country("Austria", "AT", getFlagEmoji("AT")),
        Country("Azerbaijan", "AZ", getFlagEmoji("AZ")),
        Country("Bahamas", "BS", getFlagEmoji("BS")),
        Country("Bahrain", "BH", getFlagEmoji("BH")),
        Country("Bangladesh", "BD", getFlagEmoji("BD")),
        Country("Barbados", "BB", getFlagEmoji("BB")),
        Country("Belarus", "BY", getFlagEmoji("BY")),
        Country("Belgium", "BE", getFlagEmoji("BE")),
        Country("Belize", "BZ", getFlagEmoji("BZ")),
        Country("Benin", "BJ", getFlagEmoji("BJ")),
        Country("Bermuda", "BM", getFlagEmoji("BM")),
        Country("Bhutan", "BT", getFlagEmoji("BT")),
        Country("Bolivia", "BO", getFlagEmoji("BO")),
        Country("Bosnia and Herzegovina", "BA", getFlagEmoji("BA")),
        Country("Botswana", "BW", getFlagEmoji("BW")),
        Country("Brazil", "BR", getFlagEmoji("BR")),
        Country("British Indian Ocean Territory", "IO", getFlagEmoji("IO")),
        Country("British Virgin Islands", "VG", getFlagEmoji("VG")),
        Country("Brunei", "BN", getFlagEmoji("BN")),
        Country("Bulgaria", "BG", getFlagEmoji("BG")),
        Country("Burkina Faso", "BF", getFlagEmoji("BF")),
        Country("Burundi", "BI", getFlagEmoji("BI")),
        Country("Cambodia", "KH", getFlagEmoji("KH")),
        Country("Cameroon", "CM", getFlagEmoji("CM")),
        Country("Canada", "CA", getFlagEmoji("CA")),
        Country("Cape Verde", "CV", getFlagEmoji("CV")),
        Country("Cayman Islands", "KY", getFlagEmoji("KY")),
        Country("Central African Republic", "CF", getFlagEmoji("CF")),
        Country("Chad", "TD", getFlagEmoji("TD")),
        Country("Chile", "CL", getFlagEmoji("CL")),
        Country("China", "CN", getFlagEmoji("CN")),
        Country("Christmas Island", "CX", getFlagEmoji("CX")),
        Country("Cocos Islands", "CC", getFlagEmoji("CC")),
        Country("Colombia", "CO", getFlagEmoji("CO")),
        Country("Comoros", "KM", getFlagEmoji("KM")),
        Country("Cook Islands", "CK", getFlagEmoji("CK")),
        Country("Costa Rica", "CR", getFlagEmoji("CR")),
        Country("Croatia", "HR", getFlagEmoji("HR")),
        Country("Cuba", "CU", getFlagEmoji("CU")),
        Country("Curacao", "CW", getFlagEmoji("CW")),
        Country("Cyprus", "CY", getFlagEmoji("CY")),
        Country("Czech Republic", "CZ", getFlagEmoji("CZ")),
        Country("Democratic Republic of the Congo", "CD", getFlagEmoji("CD")),
        Country("Denmark", "DK", getFlagEmoji("DK")),
        Country("Djibouti", "DJ", getFlagEmoji("DJ")),
        Country("Dominica", "DM", getFlagEmoji("DM")),
        Country("Dominican Republic", "DO", getFlagEmoji("DO")),
        Country("East Timor", "TL", getFlagEmoji("TL")),
        Country("Ecuador", "EC", getFlagEmoji("EC")),
        Country("Egypt", "EG", getFlagEmoji("EG")),
        Country("El Salvador", "SV", getFlagEmoji("SV")),
        Country("Equatorial Guinea", "GQ", getFlagEmoji("GQ")),
        Country("Eritrea", "ER", getFlagEmoji("ER")),
        Country("Estonia", "EE", getFlagEmoji("EE")),
        Country("Ethiopia", "ET", getFlagEmoji("ET")),
        Country("Falkland Islands", "FK", getFlagEmoji("FK")),
        Country("Faroe Islands", "FO", getFlagEmoji("FO")),
        Country("Fiji", "FJ", getFlagEmoji("FJ")),
        Country("Finland", "FI", getFlagEmoji("FI")),
        Country("France", "FR", getFlagEmoji("FR")),
        Country("French Polynesia", "PF", getFlagEmoji("PF")),
        Country("Gabon", "GA", getFlagEmoji("GA")),
        Country("Gambia", "GM", getFlagEmoji("GM")),
        Country("Georgia", "GE", getFlagEmoji("GE")),
        Country("Germany", "DE", getFlagEmoji("DE")),
        Country("Ghana", "GH", getFlagEmoji("GH")),
        Country("Gibraltar", "GI", getFlagEmoji("GI")),
        Country("Greece", "GR", getFlagEmoji("GR")),
        Country("Greenland", "GL", getFlagEmoji("GL")),
        Country("Grenada", "GD", getFlagEmoji("GD")),
        Country("Guam", "GU", getFlagEmoji("GU")),
        Country("Guatemala", "GT", getFlagEmoji("GT")),
        Country("Guernsey", "GG", getFlagEmoji("GG")),
        Country("Guinea", "GN", getFlagEmoji("GN")),
        Country("Guinea-Bissau", "GW", getFlagEmoji("GW")),
        Country("Guyana", "GY", getFlagEmoji("GY")),
        Country("Haiti", "HT", getFlagEmoji("HT")),
        Country("Honduras", "HN", getFlagEmoji("HN")),
        Country("Hong Kong", "HK", getFlagEmoji("HK")),
        Country("Hungary", "HU", getFlagEmoji("HU")),
        Country("Iceland", "IS", getFlagEmoji("IS")),
        Country("India", "IN", getFlagEmoji("IN")),
        Country("Indonesia", "ID", getFlagEmoji("ID")),
        Country("Iran", "IR", getFlagEmoji("IR")),
        Country("Iraq", "IQ", getFlagEmoji("IQ")),
        Country("Ireland", "IE", getFlagEmoji("IE")),
        Country("Isle of Man", "IM", getFlagEmoji("IM")),
        Country("Israel", "IL", getFlagEmoji("IL")),
        Country("Italy", "IT", getFlagEmoji("IT")),
        Country("Ivory Coast", "CI", getFlagEmoji("CI")),
        Country("Jamaica", "JM", getFlagEmoji("JM")),
        Country("Japan", "JP", getFlagEmoji("JP")),
        Country("Jersey", "JE", getFlagEmoji("JE")),
        Country("Jordan", "JO", getFlagEmoji("JO")),
        Country("Kazakhstan", "KZ", getFlagEmoji("KZ")),
        Country("Kenya", "KE", getFlagEmoji("KE")),
        Country("Kiribati", "KI", getFlagEmoji("KI")),
        Country("Kosovo", "XK", getFlagEmoji("XK")),
        Country("Kuwait", "KW", getFlagEmoji("KW")),
        Country("Kyrgyzstan", "KG", getFlagEmoji("KG")),
        Country("Laos", "LA", getFlagEmoji("LA")),
        Country("Latvia", "LV", getFlagEmoji("LV")),
        Country("Lebanon", "LB", getFlagEmoji("LB")),
        Country("Lesotho", "LS", getFlagEmoji("LS")),
        Country("Liberia", "LR", getFlagEmoji("LR")),
        Country("Libya", "LY", getFlagEmoji("LY")),
        Country("Liechtenstein", "LI", getFlagEmoji("LI")),
        Country("Lithuania", "LT", getFlagEmoji("LT")),
        Country("Luxembourg", "LU", getFlagEmoji("LU")),
        Country("Macau", "MO", getFlagEmoji("MO")),
        Country("Macedonia", "MK", getFlagEmoji("MK")),
        Country("Madagascar", "MG", getFlagEmoji("MG")),
        Country("Malawi", "MW", getFlagEmoji("MW")),
        Country("Malaysia", "MY", getFlagEmoji("MY")),
        Country("Maldives", "MV", getFlagEmoji("MV")),
        Country("Mali", "ML", getFlagEmoji("ML")),
        Country("Malta", "MT", getFlagEmoji("MT")),
        Country("Marshall Islands", "MH", getFlagEmoji("MH")),
        Country("Mauritania", "MR", getFlagEmoji("MR")),
        Country("Mauritius", "MU", getFlagEmoji("MU")),
        Country("Mexico", "MX", getFlagEmoji("MX")),
        Country("Micronesia", "FM", getFlagEmoji("FM")),
        Country("Moldova", "MD", getFlagEmoji("MD")),
        Country("Monaco", "MC", getFlagEmoji("MC")),
        Country("Mongolia", "MN", getFlagEmoji("MN")),
        Country("Montenegro", "ME", getFlagEmoji("ME")),
        Country("Montserrat", "MS", getFlagEmoji("MS")),
        Country("Morocco", "MA", getFlagEmoji("MA")),
        Country("Mozambique", "MZ", getFlagEmoji("MZ")),
        Country("Myanmar", "MM", getFlagEmoji("MM")),
        Country("Namibia", "NA", getFlagEmoji("NA")),
        Country("Nauru", "NR", getFlagEmoji("NR")),
        Country("Nepal", "NP", getFlagEmoji("NP")),
        Country("Netherlands", "NL", getFlagEmoji("NL")),
        Country("New Caledonia", "NC", getFlagEmoji("NC")),
        Country("New Zealand", "NZ", getFlagEmoji("NZ")),
        Country("Nicaragua", "NI", getFlagEmoji("NI")),
        Country("Niger", "NE", getFlagEmoji("NE")),
        Country("Nigeria", "NG", getFlagEmoji("NG")),
        Country("Niue", "NU", getFlagEmoji("NU")),
        Country("North Korea", "KP", getFlagEmoji("KP")),
        Country("Northern Mariana Islands", "MP", getFlagEmoji("MP")),
        Country("Norway", "NO", getFlagEmoji("NO")),
        Country("Oman", "OM", getFlagEmoji("OM")),
        Country("Pakistan", "PK", getFlagEmoji("PK")),
        Country("Palau", "PW", getFlagEmoji("PW")),
        Country("Palestine", "PS", getFlagEmoji("PS")),
        Country("Panama", "PA", getFlagEmoji("PA")),
        Country("Papua New Guinea", "PG", getFlagEmoji("PG")),
        Country("Paraguay", "PY", getFlagEmoji("PY")),
        Country("Peru", "PE", getFlagEmoji("PE")),
        Country("Philippines", "PH", getFlagEmoji("PH")),
        Country("Pitcairn", "PN", getFlagEmoji("PN")),
        Country("Poland", "PL", getFlagEmoji("PL")),
        Country("Portugal", "PT", getFlagEmoji("PT")),
        Country("Puerto Rico", "PR", getFlagEmoji("PR")),
        Country("Qatar", "QA", getFlagEmoji("QA")),
        Country("Republic of the Congo", "CG", getFlagEmoji("CG")),
        Country("Romania", "RO", getFlagEmoji("RO")),
        Country("Russia", "RU", getFlagEmoji("RU")),
        Country("Rwanda", "RW", getFlagEmoji("RW")),
        Country("Saint Barthelemy", "BL", getFlagEmoji("BL")),
        Country("Saint Helena", "SH", getFlagEmoji("SH")),
        Country("Saint Kitts and Nevis", "KN", getFlagEmoji("KN")),
        Country("Saint Lucia", "LC", getFlagEmoji("LC")),
        Country("Saint Martin", "MF", getFlagEmoji("MF")),
        Country("Saint Pierre and Miquelon", "PM", getFlagEmoji("PM")),
        Country("Saint Vincent and the Grenadines", "VC", getFlagEmoji("VC")),
        Country("Samoa", "WS", getFlagEmoji("WS")),
        Country("San Marino", "SM", getFlagEmoji("SM")),
        Country("Sao Tome and Principe", "ST", getFlagEmoji("ST")),
        Country("Saudi Arabia", "SA", getFlagEmoji("SA")),
        Country("Senegal", "SN", getFlagEmoji("SN")),
        Country("Serbia", "RS", getFlagEmoji("RS")),
        Country("Seychelles", "SC", getFlagEmoji("SC")),
        Country("Sierra Leone", "SL", getFlagEmoji("SL")),
        Country("Singapore", "SG", getFlagEmoji("SG")),
        Country("Sint Maarten", "SX", getFlagEmoji("SX")),
        Country("Slovakia", "SK", getFlagEmoji("SK")),
        Country("Slovenia", "SI", getFlagEmoji("SI")),
        Country("Solomon Islands", "SB", getFlagEmoji("SB")),
        Country("Somalia", "SO", getFlagEmoji("SO")),
        Country("South Africa", "ZA", getFlagEmoji("ZA")),
        Country("South Korea", "KR", getFlagEmoji("KR")),
        Country("South Sudan", "SS", getFlagEmoji("SS")),
        Country("South Sudan", "SS", getFlagEmoji("SS")),
        Country("Spain", "ES", getFlagEmoji("ES")),
        Country("Sri Lanka", "LK", getFlagEmoji("LK")),
        Country("Sudan", "SD", getFlagEmoji("SD")),
        Country("Suriname", "SR", getFlagEmoji("SR")),
        Country("Svalbard and Jan Mayen", "SJ", getFlagEmoji("SJ")),
        Country("Swaziland", "SZ", getFlagEmoji("SZ")),
        Country("Sweden", "SE", getFlagEmoji("SE")),
        Country("Switzerland", "CH", getFlagEmoji("CH")),
        Country("Syria", "SY", getFlagEmoji("SY")),
        Country("Taiwan", "TW", getFlagEmoji("TW")),
        Country("Tajikistan", "TJ", getFlagEmoji("TJ")),
        Country("Tanzania", "TZ", getFlagEmoji("TZ")),
        Country("Thailand", "TH", getFlagEmoji("TH")),
        Country("Togo", "TG", getFlagEmoji("TG")),
        Country("Tokelau", "TK", getFlagEmoji("TK")),
        Country("Tonga", "TO", getFlagEmoji("TO")),
        Country("Trinidad and Tobago", "TT", getFlagEmoji("TT")),
        Country("Tunisia", "TN", getFlagEmoji("TN")),
        Country("Turkey", "TR", getFlagEmoji("TR")),
        Country("Turkmenistan", "TM", getFlagEmoji("TM")),
        Country("Turks and Caicos Islands", "TC", getFlagEmoji("TC")),
        Country("Tuvalu", "TV", getFlagEmoji("TV")),
        Country("U.S. Virgin Islands", "VI", getFlagEmoji("VI")),
        Country("Uganda", "UG", getFlagEmoji("UG")),
        Country("Ukraine", "UA", getFlagEmoji("UA")),
        Country("United Arab Emirates", "AE", getFlagEmoji("AE")),
        Country("United Kingdom", "GB", getFlagEmoji("GB")),
        Country("United States", "US", getFlagEmoji("US")),
        Country("Uruguay", "UY", getFlagEmoji("UY")),
        Country("Uzbekistan", "UZ", getFlagEmoji("UZ")),
        Country("Vanuatu", "VU", getFlagEmoji("VU")),
        Country("Vatican", "VA", getFlagEmoji("VA")),
        Country("Venezuela", "VE", getFlagEmoji("VE")),
        Country("Vietnam", "VN", getFlagEmoji("VN")),
        Country("Wallis and Futuna", "WF", getFlagEmoji("WF")),
        Country("Western Sahara", "EH", getFlagEmoji("EH")),
        Country("Yemen", "YE", getFlagEmoji("YE")),
        Country("Zambia", "ZM", getFlagEmoji("ZM")),
        Country("Zimbabwe", "ZW", getFlagEmoji("ZW"))
    )

    /**
     * Find country by ISO code
     * @param code ISO 3166-1 alpha-2 country code
     * @return Country object or null if not found
     */
    fun findByCode(code: String): Country? {
        return getAllCountries().find { it.code.equals(code, ignoreCase = true) }
    }

    /**
     * Find countries by name (partial match)
     * @param name country name or part of it
     * @return List of matching countries
     */
    fun findByName(name: String): List<Country> {
        return getAllCountries().filter {
            it.name.contains(name, ignoreCase = true)
        }
    }
}